Log errors prior to Logout
hashicorp/packer-plugin-vsphere pull request #315
Opened 2023-10-31 00:16 UTC by bFekete

# What

- Adding additional logging 
- Separate method for Logout

# Why

- Ran into a panic when attempting to create a vSphere template and import into a content library. Noticed there weren't any helpful logs to help troubleshoot.
    - `panic: runtime error: invalid memory address or nil pointer dereference` ..... vm.go:945
    - https://github.com/hashicorp/packer-plugin-vsphere/blob/91e51c0b744025ca8554df6779e12b7f6f8c25f9/builder/vsphere/driver/vm.go#L943-L947

2023-10-31 00:16 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer-plugin-vsphere?pullRequest=315)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer-plugin-vsphere?pullRequest=315)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer-plugin-vsphere?pullRequest=315).</sub>

2023-10-31 02:28 UTC, tenthirtyam commented
Thank you for adding and linking!

2023-10-31 02:45 UTC, tenthirtyam commented
@lbajolet-hashicorp and @nywilken - I'll test this one for the crew this week and report back.

2023-10-31 11:04 UTC, nywilken commented
> @lbajolet-hashicorp and @nywilken - I'll test this one for the crew this week and report back.

Sounds good thank you @tenthirtyam

2023-11-04 04:02 UTC, tenthirtyam commented on builder/vsphere/driver/vm.go
> +		log.Printf("can not find content library due to %v", err)
```suggestion
		log.Printf("cannot find content library: %v", err)
```

2023-11-04 04:08 UTC, tenthirtyam requested changes
In Go, it's better to use "cannot" instead of "can not". 

I've made suggestions to update each to look more like the following:

```go
log.Printf("cannot find datastore: %v", err)
```

This message is more concise and follows Go's conventions. The colon (:) is used to separate the error message from the error itself, which makes it easier to understand what caused the error.

2023-11-04 04:08 UTC, tenthirtyam commented on builder/vsphere/driver/vm.go
> +				log.Printf("can not update content library due to %v", err)
```suggestion
				log.Printf("cannot update content library: %v", err)
```

2023-11-04 04:08 UTC, tenthirtyam commented on builder/vsphere/driver/vm.go
> +		log.Printf("can not find content library due to %v", err)
```suggestion
		log.Printf("cannot find content library: %v", err)
```

2023-11-04 04:08 UTC, tenthirtyam commented on builder/vsphere/driver/vm.go
> +			log.Printf("can not find resource pool due to %v", err)
```suggestion
			log.Printf("cannot find resource pool: %v", err)
```

2023-11-04 04:08 UTC, tenthirtyam commented on builder/vsphere/driver/vm.go
> +			log.Printf("can not find datastore due to %v", err)
```suggestion
			log.Printf("cannot find datastore: %v", err)
```

2023-11-04 04:08 UTC, tenthirtyam commented on builder/vsphere/driver/vm.go
> +			log.Printf("can not find folder due to %v", err)
```suggestion
			llog.Printf("cannot find folder: %v", err)
```

2023-11-04 04:08 UTC, tenthirtyam commented on builder/vsphere/driver/vm.go
> +			log.Printf("can not find host due to %v", err)
```suggestion
			log.Printf("cannot find host: %v", err)
```

2023-11-04 04:08 UTC, tenthirtyam commented on builder/vsphere/driver/vm.go
> +		log.Printf("can not create template due to %v", err)
```suggestion
		log.Printf("cannot create template: %v", err)
```

2023-11-04 04:08 UTC, tenthirtyam commented on builder/vsphere/driver/vm.go
> +		log.Printf("can not find content library due to %v", err)
```suggestion
		log.Printf("cannot find content library: %v", err)
```

2023-11-04 04:08 UTC, tenthirtyam commented on builder/vsphere/driver/vm.go
> +		log.Printf("can not logout due to %s ", err.Error())
```suggestion
		log.Printf("cannot logout: %s ", err.Error())
```

2023-11-04 09:41 UTC, tenthirtyam approved these changes
LGTM!

2023-11-06 17:03 UTC, nywilken approved these changes
This looks good to me. Thanks for the fix @bFekete!
 @tenthirtyam thanks for the review and suite of testing. Much appreciated.

2023-11-06 17:04 UTC, merged