feat: add support for VirtualPrecisionClock
hashicorp/packer-plugin-vsphere pull request #367
Opened 2024-02-26 15:17 UTC by xtalkme

These changes allow you to define a VirtualPrecisionClock device.
Closes #354

2024-02-26 15:17 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer-plugin-vsphere?pullRequest=367)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer-plugin-vsphere?pullRequest=367)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer-plugin-vsphere?pullRequest=367).</sub>

2024-02-26 15:35 UTC, tenthirtyam commented on builder/vsphere/common/step_hardware.go
> +		errs = append(errs, fmt.Errorf("'VirtualPrecisionClock' must be '', 'ptp', 'ntp' or 'none'"))
```suggestion
		errs = append(errs, fmt.Errorf("'VirtualPrecisionClock' must be '', 'ptp', 'ntp', or 'none'"))
```

2024-02-26 15:35 UTC, tenthirtyam commented on builder/vsphere/common/step_hardware_test.go
> +			expectedErrMsg: "'VirtualPrecisionClock' must be '', 'ptp', 'ntp' or 'none'",
```suggestion
			expectedErrMsg: "'VirtualPrecisionClock' must be '', 'ptp', 'ntp', or 'none'",
```

2024-02-26 15:43 UTC, tenthirtyam commented on .web-docs/components/builder/vsphere-clone/README.md
> +- `VirtualPrecisionClock` (string) - Add precision clock device for virtual machine. Defaults to `none`.
Would prefer either `precision_clock` or `precision_clock` as it it referred to in vSphere (docs and UI...)

```suggestion
- `precision_clock` (string) - Add a precision clock device for virtual machine. Defaults to `none`.
```

2024-02-26 15:43 UTC, tenthirtyam commented on .web-docs/components/builder/vsphere-iso/README.md
> +- `VirtualPrecisionClock` (string) - Add precision clock device for virtual machine. Defaults to `none`.
```suggestion
- `precision_clock` (string) - Add precision clock device for virtual machine. Defaults to `none`.
```

2024-02-26 15:44 UTC, tenthirtyam commented on builder/vsphere/clone/config.hcl2spec.go
> +	VirtualPrecisionClock           *string                                     `mapstructure:"VirtualPrecisionClock" cty:"VirtualPrecisionClock" hcl:"VirtualPrecisionClock"`
```suggestion
	VirtualPrecisionClock           *string                                     `mapstructure:"precision_clock" cty:"precision_clock" hcl:"precision_clock"`
```

2024-02-26 15:44 UTC, tenthirtyam commented on builder/vsphere/clone/config.hcl2spec.go
> +		"VirtualPrecisionClock":          &hcldec.AttrSpec{Name: "VirtualPrecisionClock", Type: cty.String, Required: false},
```suggestion
		"precision_clock":          &hcldec.AttrSpec{Name: "precision_clock", Type: cty.String, Required: false},
```

2024-02-26 15:44 UTC, tenthirtyam commented on builder/vsphere/common/step_hardware.go
> +	VirtualPrecisionClock string `mapstructure:"VirtualPrecisionClock"`
```suggestion
	VirtualPrecisionClock string `mapstructure:"precision_clock"`
```

2024-02-26 15:45 UTC, tenthirtyam commented on builder/vsphere/common/step_hardware.hcl2spec.go
> +	VirtualPrecisionClock *string `mapstructure:"VirtualPrecisionClock" cty:"VirtualPrecisionClock" hcl:"VirtualPrecisionClock"`
```suggestion
	VirtualPrecisionClock *string `mapstructure:"precision_clock" cty:"precision_clock" hcl:"precision_clock"`
```

2024-02-26 15:46 UTC, tenthirtyam commented on builder/vsphere/common/step_hardware.hcl2spec.go
> +		"VirtualPrecisionClock": &hcldec.AttrSpec{Name: "VirtualPrecisionClock", Type: cty.String, Required: false},
```suggestion
		"VirtualPrecisionClock": &hcldec.AttrSpec{Name: "precision_clock", Type: cty.String, Required: false},
```

2024-02-26 15:46 UTC, tenthirtyam commented on builder/vsphere/common/step_hardware_test.go
> +			name: "Validate 'VirtualPrecisionClock'",
```suggestion
			name: "Validate 'precision_clock'",
```

2024-02-26 15:46 UTC, tenthirtyam commented on builder/vsphere/common/step_hardware_test.go
> +				VirtualPrecisionClock: "ntp",
```suggestion
				precision_clock: "ntp",
```

2024-02-26 15:46 UTC, tenthirtyam commented on builder/vsphere/common/step_hardware_test.go
> +			name: "Validate 'VirtualPrecisionClock' and invalid option",
```suggestion
			name: "Validate 'precision_clock' and invalid option",
```

2024-02-26 15:47 UTC, tenthirtyam commented on builder/vsphere/common/step_hardware_test.go
> +				VirtualPrecisionClock: "invalid",
```suggestion
				precision_clockk: "invalid",
```

2024-02-26 15:47 UTC, tenthirtyam commented on builder/vsphere/driver/vm_test.go
> +		VirtualPrecisionClock: "ntp",
```suggestion
		precision_clock: "ntp",
```

2024-02-26 15:59 UTC, tenthirtyam requested changes
Suggested changes provided. Additinally, the following privledges would also need to be noted in the documentation.

- `Virtual Machine.Configuration`: Add or remove device
- `Virtual machine.Configuration:` Modify device settings

2024-02-26 15:59 UTC, tenthirtyam commented on docs-partials/builder/vsphere/common/HardwareConfig-not-required.mdx
> +- `VirtualPrecisionClock` (string) - Add precision clock device for virtual machine. Defaults to `none`.
```suggestion
- `precision_clock` (string) - Add precision clock device for virtual machine. Defaults to `none`.
```

2024-02-26 19:42 UTC, tenthirtyam commented on .web-docs/components/builder/vsphere-iso/README.md
These are auto-generated and do not need a manual update.

2024-02-26 19:44 UTC, xtalkme commented on .web-docs/components/builder/vsphere-clone/README.md
Yes, my bad. This github workflow/approval is very new for me, and also i kinda forgot to think....
Think i broke more in the last 10 minutes then added value.

2024-02-26 19:48 UTC, tenthirtyam commented on .web-docs/components/builder/vsphere-clone/README.md
I'm fixing these.

2024-02-26 19:57 UTC, tenthirtyam approved these changes
LGTM! Reviewed and updated as applicable.

2024-02-26 19:58 UTC, xtalkme commented
This MR started like i sorta knew what i was doing. That escalated quickly...

2024-02-26 20:20 UTC, tenthirtyam commented
Nah, great job in adding the capability. This contribution is most welcome. In fact, there is a need to do the same in the Terraform provider, too. :)

2024-02-27 16:33 UTC, nywilken approved these changes
This looks good to me. Thanks for the contribution @xtalkme 

@tenthirtyam as always thanks for the review and pushing this change forward. 💙

2024-02-27 16:33 UTC, merged