[Documentation Only] Add lsilogic-sas As Storage Controller Option
hashicorp/packer-plugin-vsphere pull request #96
Opened 2021-08-03 20:01 UTC by jonhowe

The documentation does not include the valid `disk_controller_type` of lsilogic-sas. There was an issue/pr mentioned in the jetbrains repo (https://github.com/jetbrains-infra/packer-builder-vsphere/issues/188) that led me to this conclusion.

2021-08-03 20:01 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer-plugin-vsphere?pullRequest=96)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer-plugin-vsphere?pullRequest=96)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer-plugin-vsphere?pullRequest=96).</sub>

2021-08-04 10:21 UTC, sylviamoss requested changes
Hi, this looks good but you changed the docs in a generated file. You need to make the change in [storage_config.go](https://github.com/hashicorp/packer-plugin-vsphere/blob/main/builder/vsphere/common/storage_config.go#L94) and run [make generate](https://github.com/hashicorp/packer-plugin-vsphere/blob/main/GNUmakefile#L16). 
Let me know if you need any further help with it.

2021-08-07 15:23 UTC, jonhowe commented
Thanks for the info @sylviamoss! Took me a minute to figure this all out, but I think it should be good now. If there's anything else I should do, let me know and I'll adjust.

2021-08-09 06:02 UTC, azr commented
LGTM ! Thanks

2021-08-09 06:02 UTC, merged